### ISSUE TITLE
Allow erroring when calling init

### ISSUE THREAD

**Issue by ysthakur** [Bubbler-4/TryInBrowser#5]
It would be nice to error or print something else in the `init` method itself, instead of checking a condition each time when calling `step` and stopping then. I don't know Rust, so would that be possible?

**Comment by Bubbler-4** [comment]
If you mean [this method](https://github.com/Bubbler-4/TryInBrowser/blob/eff6381d184b1ecb1ca84b3dbe04c521ecd91af9/src/languages/mod.rs#L39), the `LangContext` will be totally replaced by a WebWorker-based async runner (which doesn't require single-stepping at all) in the next update. See #2 for details.
